apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-cloud-sa
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-cloud-rbc
subjects:
- kind: ServiceAccount
  name: spring-cloud-sa
  namespace: ninckblokje
roleRef:
  kind: ClusterRole
  name: spring-cloud
  apiGroup: rbac.authorization.k8s.io