apiVersion: v1
kind: Pod
metadata:
  name: run-as
spec:
  volumes:
  - name: run-as-vol
    emptyDir: {}
  containers:
  - name: run-as
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: run-as-vol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false