apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-admin
  labels:
    app: spring-boot-admin
spec:
  containers:
  - name: spring-boot-admin
    image: ninckblokje/k8s-spring-boot-admin:1.0.0
    ports:
      - containerPort: 8080
  serviceAccountName: spring-cloud-sa