kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ninckblokje-pod-ro-rbc
subjects:
- kind: ServiceAccount
  name: ninckblokje-pod-ro-sa
  namespace: ninckblokje
roleRef:
  kind: ClusterRole
  name: ninckblokje-pod-ro-role
  apiGroup: rbac.authorization.k8s.io