apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: ping-pong
        image: ninckblokje/ping-pong:golang
        ports:
        - containerPort: 8080
  replicas: 1