apiVersion: v1
kind: Pod
metadata:
  name: who-was-here
  labels:
    app: who-was-here
spec:
  containers:
  - name: who-was-here
    image: ninckblokje/whowashere
    ports:
      - containerPort: 8080