apiVersion: apps/v1
kind: Deployment
metadata:
  name: who-was-here
spec:
  selector:
    matchLabels:
      app: who-was-here
  template:
    metadata:
      labels:
        app: who-was-here
    spec:
      containers:
      - name: who-was-here
        image: ninckblokje/whowashere
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: who-was-here
        livenessProbe:
          httpGet:
            path: /actuator/info
            port: 8080
          initialDelaySeconds: 65
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 95
  replicas: 3
---
apiVersion: v1
kind: Service
metadata:
  name: who-was-here
spec:
  selector:
    app: who-was-here
  ports:
  - port: 80
    targetPort: 8080