apiVersion: batch/v1
kind: Job
metadata:
  name: ping-pong-once
spec:
  template:
    spec:
      containers:
      - name: ping-pong-once
        image: centos:7.6.1810
        command: ["/bin/bash"]
        args: ["-c", "yum install -y curl; curl http://ping-pong/ping"]
      restartPolicy: Never